"""empty message

Revision ID: 686c749b249b
Revises: 
Create Date: 2020-02-24 13:14:05.744278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686c749b249b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos','completed',nullable=False)
    # ### end Alembic commands ###
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
