"""empty message

Revision ID: 595071bf301e
Revises: a80e1ae38879
Create Date: 2020-02-28 20:25:58.253668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595071bf301e'
down_revision = 'a80e1ae38879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
